In [74]:
import numpy as np

array = np.array([[0, 0, 0, 0, 0, 0,],
                  [0, 0, 0, 0, 0, 0,],
                  [0, 0, 0, 0, 0, 0,],
                  [0, 0, 1, 1, 1, 0,],
                  [0, 0, 0, 0, 0, 0,],
                  [0, 0, 0, 0, 0, 0,],])


In [77]:
down = (array[:, :-1] == 1) & (array[:, 1:] == 0)
array[:, :-1][down] = 0
array[:, 1:][down] = 1


print(array)
print(down)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False  True]
 [False False False False False]
 [False False False False False]]
